### ISSUE TITLE
pluggy._manager.PluginValidationError: unknown hook 'pytest_cmdline_preparse'

### ISSUE THREAD

**Issue by kevinyuan** [pymtl/pymtl3#285]
Dear PyMTL3 team,

I received the following error when run the test in examples dir:

```
> pytest
 
================================================================== test session starts ==================================================================
platform linux -- Python 3.10.12, pytest-8.3.4, pluggy-1.5.0
rootdir: /home/kevin/works/ide/pymtl3
configfile: pytest.ini
plugins: hypothesis-6.122.3, pymtl3-3.1.16
collected 274 items                                                                                                                                     
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/kevin/works/ide/.venv/lib/python3.10/site-packages/_pytest/main.py", line 283, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/kevin/works/ide/.venv/lib/python3.10/site-packages/_pytest/main.py", line 336, in _main
...
INTERNALERROR> pluggy._manager.PluginValidationError: unknown hook 'pytest_cmdline_preparse' in plugin <module 'pytest_plugin.pytest_pymtl3' from '/home/kevin/works/ide/.venv/lib/python3.10/site-packages/pytest_plugin/pytest_pymtl3.py'>
```

**Comment by cbatten** [comment]
Fixed:

- https://github.com/pymtl/pymtl3/commit/eea5ff49e06b303123097dc4d9e163790c0f58d6
